name: Manually trigger issue creation for standard set up

# This is a manually triggered workflow
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-on-github
on:
  workflow_dispatch:

jobs:
  # This runs a single job that creates issues from files
  createIssuesFromFile:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Check out
      - uses: actions/checkout@v3

      # Issue for turning on GitHub pages
      - name: Create GitHub Pages issue
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Turn on GitHub Pages
          content-filepath: ./setup-issue-templates/gh-pages.md
          labels: automated training issue

      # Issue for turning on branch protection
      - name: Create branch protection issue
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Set up branch protection - pull requests required
          content-filepath: ./setup-issue-templates/branch-protection.md
          labels: automated training issue

      # Issue updating `_config.yaml`
      - name: Create issue for _config.yaml
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Update _config.yaml to use values relevant to this workshop
          content-filepath: ./setup-issue-templates/update-config.md
          labels: automated training issue

      # Issue for adding PDF versions of slides
      - name: Create issue for slides
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Add PDF versions of slides to `slides`
          content-filepath: ./setup-issue-templates/pdf-slides.md
          labels: automated training issue, slides

      # Issue for creating a draft version of schedule
      - name: Create draft schedule issue
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Draft version of schedule
          content-filepath: ./setup-issue-templates/draft-schedule.md
          labels: automated training issue, schedule

      # Issue for updating config with training-specific release values
      - name: Create issue for updating config with training-specific release values
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Update config to include training-specific release values
          content-filepath: ./setup-issue-templates/config-release.md
          labels: automated training issue

      # Issue for copying completed notebooks from training-modules
      - name: Create issue for copying completed notebooks
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Copy completed notebooks to training website
          content-filepath: ./setup-issue-templates/copy-completed-notebooks.md
          labels: automated training issue, blocked

      # Issue for customizing participant-information.md
      - name: Create issue for updating participant-information.md
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Update in-person logistics in `participant-information.md`
          content-filepath: ./setup-issue-templates/update-participant-information.md
          labels: automated training issue

      # Issue for creating a final version of schedule
      - name: Create final schedule issue
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Final version of schedule
          content-filepath: ./setup-issue-templates/final-schedule.md
          labels: automated training issue, schedule, blocked

      # Issue for updating README
      - name: Create issue for updating README
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Update README to be user-facing (remove instructions)
          content-filepath: ./setup-issue-templates/user-facing-readme.md
          labels: automated training issue
